name: eco_picker
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+1
  path_provider: ^2.1.4

  provider: ^6.0.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.10
  fluttertoast: ^8.0.9
  fl_chart: ^0.68.0
  path: ^1.9.0
  http_parser: ^4.0.2
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0
  share: ^2.0.4

dependency_overrides:
  geolocator_web: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/Icon.png
    - assets/google_fonts/OpenSans-ExtraBold.ttf
    - assets/google_fonts/OpenSans-Bold.ttf
    - assets/google_fonts/OpenSans-Light.ttf
    - assets/google_fonts/OpenSans-Medium.ttf
    - assets/google_fonts/OpenSans-Regular.ttf
    - assets/google_fonts/OpenSans-SemiBold.ttf
    - assets/google_fonts/Quicksand-Bold.ttf
    - assets/google_fonts/Quicksand-Medium.ttf
    - assets/google_fonts/Quicksand-Regular.ttf
    - assets/google_fonts/Quicksand-SemiBold.ttf
    - assets/images/
    - assets/map_style.json
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Icon.png"
  windows:
    generate: true
    image_path: "assets/images/Icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/Icon.png"
