name: eco_picker
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  go_router: ^14.2.1
  image_picker: ^0.8.4+4
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
